name: Build and Deploy (Production)

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

permissions:
  contents: write # Needed for gh-pages deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run type-check # Add this script if you use TypeScript

    - name: Lint
      run: npm run lint # Add this script if you use ESLint

    - name: Build and Deploy
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
